# docker-compose.yml

version: "3.8"

services:
  web:
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=financeiro.settings # Garanta que suas settings estão sendo usadas

  celery_worker:
    build: .
    command: celery -A financeiro worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web # Opcional, mas útil se o worker precisar do banco de dados do Django
    environment:
      - DJANGO_SETTINGS_MODULE=financeiro.settings

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
  flower: # NOVO SERVIÇO PARA O FLOWER
    build: .
    command: celery -A financeiro flower --port=5555 --broker=redis://redis:6379/0
    volumes:
      - .:/app
    ports:
      - "5555:5555" # Porta para acessar a interface web do Flower
    depends_on:
      - redis
      - celery_worker # Flower precisa que o worker e o broker estejam rodando
    environment:
      - DJANGO_SETTINGS_MODULE=financeiro.settings
      # Opcional: Se quiser autenticação para o Flower (RECOMENDADO PARA PRODUÇÃO)
      # - CELERY_FLOWER_USER=admin
      # - CELERY_FLOWER_PASSWORD=password
