# Generated by Django 5.2.1 on 2025-05-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fornecedor',
            new_name='FornecedorModel',
        ),
    ]
