# Generated by Django 5.2.1 on 2025-05-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
